# fly.toml app configuration file generated for fs-part-3-phonebook on 2023-07-24T12:49:34+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fs-part-3-phonebook"
primary_region = "arn"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
